# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2270d87fe628ae0fb9eb512b689f71f9c7a91c89aa699236dd23433ba8781ee937ea382edff295e8a1264d1af07f775456895ef6e34593e93f6a73fcc3451071

test:
  secret_key_base: c8fce092e9e470d071c8f56c51b821d61cb88237657fa664e936eed0ec4edf5ea818759da66a0ac681565359e799001606bf97937a2d1e61fc47bd38f75a2c37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
